[project]
name = "whisperkit-python-client"
version = "0.1.0"
description = "Python client for WhisperKit local server"
requires-python = ">=3.8"
dependencies = [
    "openai>=1.0.0",
    "requests>=2.25.0",
    "python-dotenv>=0.19.0",
    "argparse",
]
