name: Pre-Release Tests

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build-and-test-all-platforms:
    name: "Build and Test All Platforms"
    strategy:
      matrix:
        include:
          - os: macos-13-xlarge
            ios-version: "16.1" # Oldest available version
          - os: macos-14
            ios-version: "17.2" # Latest available version
    uses: ./.github/workflows/unit-tests.yml
    with:
      ios-version: ${{ matrix.ios-version }}
      macos-runner: ${{ matrix.os }}
